# netlify.toml

[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18" # o la versión de Node que uses
  REACT_APP_SUPABASE_URL = "https://lqcjprngnslazjynhrod.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxY2pwcm5nbnNsYXpqeW5ocm9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMDI0MTAsImV4cCI6MjA2MTc3ODQxMH0.wn-WbbvTAZaeuxXepBHyS8E4gsDbh_54BJcrgkO15XE" # pon aquí tu clave completa
  REACT_APP_API_URL = "https://onyra.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
