# Configuración para Netlify

# Comando de construcción para React
[build]
  base = "frontend"
  command = "npm run build" 
  publish = "build"

# Configuración para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200